### ISSUE TITLE
Progress indicator hiding logic

### ISSUE THREAD

**Issue by joshcosta** [gradebook/client#16]
The progress bar and remainders elements hide themselves at unexpected times.

Example:
- Create course of 2 rows with names and weights
- Expand 1 row to a category
- Partially complete that categories grades
- Progress bar and remainders act as if course has no entered grades

**Comment by vikaspotluri123** [comment]
@joshcosta can you spec out what should be visible and when? Then we can write tests for them and update the impl!

**Comment by vikaspotluri123** [comment]
Released in 3.0
