### ISSUE TITLE
Remove trailing zeroes across app

### ISSUE THREAD

**Issue by joshcosta** [gradebook/client#26]
Trailing zeroes after the decimal can be removed.
![image](https://user-images.githubusercontent.com/43763502/66366005-95b98980-e954-11e9-82af-9f42a076e530.png)

**Comment by ramsays** [comment]
Fixed this with the latest commit. There is now a utility function for rounding numbers properly like other languages.

**Comment by vikaspotluri123** [comment]
^ closed in 6009d95
